/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonForm: typeof import('./components/common/CommonForm.vue')['default']
    CustomTable: typeof import('./components/common/CustomTable.vue')['default']
    RegisterMessage: typeof import('./components/common/RegisterMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPanel: typeof import('./components/common/SearchPanel.vue')['default']
    SvgIcon: typeof import('./components/common/SvgIcon.vue')['default']
  }
}
